// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package surveylist

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SurveyRow() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"survey-row\"><!-- Vessel --><div class=\"survey-cell\"><div class=\"survey-cell__vessel-name\">POLAR STAR</div><div class=\"survey-cell__vessel-imo\">IMO 9233387</div></div><!-- Date --><div class=\"survey-cell\"><div class=\"survey-cell__date-main\">16 Feb 2026</div><div class=\"survey-cell__date-time\">08:45</div></div><!-- Port --><div class=\"survey-cell survey-cell--text\">Vanino, Russia</div><!-- Destination --><div class=\"survey-cell survey-cell--text\">China</div><!-- Operation --><div class=\"survey-cell\"><span class=\"badge badge--load\">Loading</span></div><!-- Cargo --><div class=\"survey-cell survey-cell--mono\">78,556.093</div><!-- Status --><div class=\"survey-cell\"><span class=\"badge badge--complete\">Complete</span></div><!-- Actions --><div class=\"survey-cell survey-cell--actions\"><button class=\"ia ia--open\" title=\"Open survey\"><svg viewBox=\"0 0 24 24\"><path d=\"M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6\"></path><polyline points=\"15 3 21 3 21 9\"></polyline><line x1=\"10\" y1=\"14\" x2=\"21\" y2=\"3\"></line></svg></button> <button class=\"ia\" title=\"More\"><svg viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"5\" r=\"1\"></circle><circle cx=\"12\" cy=\"12\" r=\"1\"></circle><circle cx=\"12\" cy=\"19\" r=\"1\"></circle></svg></button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
