package constants

// New Survey data
const (
	ConstDeclared   = "constDeclared"
	CargoDeclared   = "cargoDeclared"
	JobNumber       = "job-number"
	DSNumber        = "ds-number"
	CargoOperation  = "cargo-op"
	CargoLoading    = "loading"
	CargoDischarge  = "discharge"
	Cargo           = "cargo"
	Packing         = "packing"
	Client          = "client"
	Remarks         = "remarks"
	VesselName      = "vessel-name"
	IMO             = "imo"
	Built           = "built"
	Lightship       = "lightship"
	LBP             = "lbp"
	Breadth         = "breadth"
	Depth           = "depth"
	SummerDraft     = "summer_draft"
	SummerDWT       = "summer_dwt"
	SummerTPC       = "summer_tpc"
	SummerFreeboard = "summer_freeboard"
	MMCMethod       = "mmc_method"
	CorrMethod      = "corr_method"
	LCFDetection    = "lcf_detection"
	HoldsTotal      = "holds_total"
	CountryCode     = "country_code"
	CountryName     = "country_name"
	Flag            = "flag"
)
